#!/usr/bin/env bash

CONFIG_FILE=(~/.config/tofi/config-powermenu)

# Check whether a command exists
function command_exists() {
  command -v "$1" &> /dev/null 2>&1
}

if ! command_exists systemctl ; then
    exit 1
fi

typeset -A menu
 
menu=(
  [ Shutdown]="systemctl poweroff"
  [ Poweroff]="systemctl poweroff"
  [ Reboot]="systemctl reboot"
  [ Suspend]="systemctl suspend"
  [ Hibernate]="systemctl hibernate"
  [ Lock]="swaylock"
  [ Logout]="hyprctl dispatch exit"
  [ Cancel]=""
)

menu_nrows=${#menu[@]}

# Menu entries that may trigger a confirmation message
menu_confirm="Shutdown Reboot Hibernate Suspend Halt Logout"

launcher="tofi -c ${CONFIG_FILE}"
selection="$(printf '%s\n' "${!menu[@]}" | sort | ${launcher} )"

if [[ $? -eq 0 && ! -z ${selection} ]]; then
    hyprctl dispatch exec ${menu[$selection]}
fi
    
